### ISSUE TITLE
Morris Traversal on Binary Tree

### ISSUE THREAD

**Issue by JRahul11** [tanuj1811/damn_dsa#4]
**What is the issue?**

- [x] New algorithm
- [ ] Update to an existing algorithm
- [ ] Bug/Error
- [ ] Proposal to the Repository

**Details:**

Morris Traversal on Binary Trees. Allows tree traversals like inorder, preorder and postorder to run in constant space.
Time Complexity: O(N)
Space Complexity: O(1)

**Comment by Noobham** [comment]
hey ,
I am very new to open source , i would like contribute to this issue .
can i get details of this issue if its opened.

**Comment by tanuj1811** [comment]
Hey @Noobham ,

Glad you want to contribute and yes, this issue is not resolved yet. If you want to contribute, Just follow the steps mentioned in the [README.md](https://github.com/tanuj1811/damn_dsa/blob/main/README.md#steps-for-contribution) file.

Happy Codding :)

**Comment by Noobham** [comment]
in which file should i upload the code

**Comment by tanuj1811** [comment]
I have created the [Tree](https://github.com/tanuj1811/damn_dsa/tree/main/Tree) folder. You can upload their.

**Comment by abhikumar002** [comment]
I think I can help with this issue.
 @tanuj1811 , I would really appreciate it if you could assign me this issue with the Hacktoberfest tag so I can start contributing to this repo. Thank you and have a great Hacktoberfest.
